### ISSUE TITLE
energy_WO

### ISSUE THREAD

**Issue by ripper121** [whatnick/ATM90E26_Arduino#1]
For what is the energy_WO PIN needed?

**Comment by whatnick** [comment]
From datasheet:

WARNOUT PIN FOR 
FATAL ERROR WARNING
Fatal error warning is raised through the WarnOut pin in two cases: checksum calibration error and voltage sag.
Calibration Error
The M90E26 performs diagnosis on a regular basis for importan
t parameters such as calibration parameters and metering
configuration. When checksum is no
t correct, the CalErr[1:0] bits (
SysStatus
, 01H) are set, and both the WarnOut pin and
the IRQ pin are asserted. When checksum is not correct, the metering part does not work to prevent a large number of
pulses during power-on or any abnormal situation upon incorrect parameters. 
Voltage Sag
Voltage sag is detected when voltage is continuously below the voltage sag threshold for one cycle which starts from any
zero-crossing point. Voltage threshold is configured by the 
SagTh
 register (03H). Refer to section 
6.5
.
When voltage sag occurs, the SagWarn bit (
SysStatus
, 01H) is set and the WarnOut pin is asserted if the 
FuncEn
 register
(02H) enables voltage sag warning through the WarnOut pin. Th
is function helps reduce power-down detection circuit in
system design. In addition, the method of judging voltage sag by
 detecting AC side voltage eliminates the influence of large
capacitor in traditional rectifier circuit, and can detect voltage sag earlier

**Comment by whatnick** [comment]
This is noted in the manual. Issue closed.
