### ISSUE TITLE
ESP8266 SPI modes were unswapped, need to fix SPI code

### ISSUE THREAD

**Issue by SaintGimp** [whatnick/ATM90E26_Arduino#20]
Previously the SPI implementation for the ESP8266 had [mode 2 and 3 swapped](https://github.com/esp8266/Arduino/issues/2416).  The ATM90E26 code checks if it's compiling for ESP8266 and specifies mode 2 (which is really mode 3) in that case.  However, the mode swap has been [fixed in the ESP8266 board files](https://github.com/esp8266/Arduino/pull/5948), so the ATM90E26 code should now just specify mode 3 in all cases.  The code as it is right now won't run on ESP8266 until it's fixed.

**Comment by whatnick** [comment]
Thanks so much for the heads up. Would it be possible to create an
ESP-Arduino version check + mode selection patch to keep it running for
those who have not upgraded the board support yet ?

I am working on this project again. I will try to implement it. If you have
time I would love a patch.
