### ISSUE TITLE
Unable to communicate with ATM90E26

### ISSUE THREAD

**Issue by maheshbhome** [whatnick/ATM90E26_Arduino#24]
Hi All,
         I am working with ATM90E26 metering IC. I have implemented circuit as per Application note,  use Arduino uno board   and used source code from whatnick/ATM90E26_Arduino but getting 00 reply for every read as per source code, please help me out on same.

**Comment by whatnick** [comment]
Atm90e26 is a 3.3v device. I believe UNO is 5v. Need more details on your
exact circuit and SPI vs UART mode. Also please use a logic analyzer to
check signals on you wires.

**Comment by maheshbhome** [comment]
Thanks for your reply, Now I have connected ATM90E26 to Beaglebone black wireless using SPI. 
 I have some queries, 
1) ATM90E26 need to be calibrated or it can be run without calibration.
2) if Calibration required, then  is it  ok that values set as per excel sheet provided by you in arduino code.
3 ) [I](url) am able to read voltage  and frequency but every time I get new values.


![ATM90e26-application circuit](https://user-images.githubusercontent.com/66674816/94234738-e6d8d980-ff27-11ea-94b3-481c1265779b.PNG)

**Comment by maheshbhome** [comment]
one more query , is shunt resistance is necessary in circuit.

**Comment by maheshbhome** [comment]
hi, I am unable to read APenergy register kindly help me out on same.

**Comment by Yogesh-2897** [comment]
Hii, I have implemented the circuit as mentioned in the application note for ATM90e26, But i am not able to communicate with the IC through spi. Please help
